### ISSUE TITLE
[1.17] Tick Overflow error when alloying items.

### ISSUE THREAD

**Issue by ffuentesm** [HexagonNico/ReworkedMetals#8] opened 2021-11-19 21:16 UTC
I added some ingots to smelt and once I shift-click the coal the game crashed.
Could you give Polymorph support so that the same ingot from different mods can be chosen when smelted? 

Versions (Be specific, do not write "latest"):
Polymorph: polymorph-forge-1.17.1-0.31.jar
Reworked Metals: reworkedmetals-1.1.1-1.17.1.jar
Forge/Fabric: 37.0.109

Observed Behavior:
Game crashes when shift-click on coal

Expected Behavior:
Items would be smelted

Crash Log: [bytebin] https://bytebin.lucko.me/h13CmCVghs
![image](https://user-images.githubusercontent.com/44974827/142692105-3bc63665-ffea-4c94-8d76-dcd162236b4a.png)

**Comment by HexagonNico** [comment] 2021-11-20 15:22
Hi. Unfortunately I'm unable to reproduce the issue, but by looking at the log I might have found the cause of the crash. I'll make sure to fix it in the next update.

**Comment by HexagonNico** [comment] 2021-12-25 20:15
Hi. Since this bug has been long fixed and hasn't been reported since, I'm closing this issue.

**Closed as completed by HexagonNico** 2021-12-25 20:15 UTC
